# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
inhibit_all_warnings!
target 'WanQuan-iOS' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

#pod 'MWPhotoBrowser'
pod 'Reveal-SDK', :configurations => ['Debug']
pod 'AFNetworking'
pod 'SDWebImage'
pod 'Masonry'
pod 'YYModel'
pod 'YYText'
pod 'BaiduMapKit'
pod 'SVProgressHUD'
pod 'HyphenateLite_CN'
pod 'UMengAnalytics'
pod 'SKFCamera'
pod 'TZImagePickerController'
pod 'WechatOpenSDK'
#pod 'ZYQAssetPickerController'
pod 'IQKeyboardManager'
pod 'DZNEmptyDataSet'
pod 'FDFullscreenPopGesture'
pod 'MBProgressHUD'
pod 'Bugly'
pod 'MJRefresh'
pod 'GPUImage'
pod 'FDStackView'
 # Pods for WanQuan-iOS

end
